// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHqxoHrIDlWww9PI0H9TY4yFU7a2jGns',
    appId: '1:658671041011:android:88094bd9d21836530fba86',
    messagingSenderId: '658671041011',
    projectId: 'plant-shop-e48a2',
    databaseURL: 'https://plant-shop-e48a2-default-rtdb.firebaseio.com',
    storageBucket: 'plant-shop-e48a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIOIWD0qnUpF6bX-gOWv49OjG8t3lwQI',
    appId: '1:658671041011:ios:cc17cc2d27f7eb730fba86',
    messagingSenderId: '658671041011',
    projectId: 'plant-shop-e48a2',
    databaseURL: 'https://plant-shop-e48a2-default-rtdb.firebaseio.com',
    storageBucket: 'plant-shop-e48a2.appspot.com',
    iosBundleId: 'com.flutterworkshop.plantshop',
  );
}
